<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="microsoft.entityframeworkcore" Version="10.0.9" />
    <PackageReference Include="microsoft.extensions.dependencyinjection" Version="10.0.9" />
    <PackageReference Include="oracle.entityframeworkcore" Version="10.23.26200" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ApplicationService\ApplicationService.csproj" />
  </ItemGroup>

</Project>
