<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>e5f5586b-1e19-42dd-9421-18f70f2171c5</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="asp.versioning.mvc" Version="10.0.0" />
    <PackageReference Include="asp.versioning.mvc.apiexplorer" Version="10.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8" />
    <PackageReference Include="Swashbuckle.aspnetcore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ApplicationService\ApplicationService.csproj" />
    <ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
  </ItemGroup>

</Project>
